# окружений в котором запускают
env: "local" # local, dev, prod

# настройки redis
redis:
  address: "localhost:6379"
  password: ""
  # номер базы(по умолчанию 0)
  db: 0

# настройки http сервера
http_server:
  address: "localhost:8083"
  # время на чтение запроса и такое же время на отправку ответа
  timeout: 4s
  # время жизни соединения с клиентом, чтобы заного не создвать соединение
  # если будет повторный запрос от тогоже клиента
  idle_timeout: 60s
  user: "myuser"
  password: "mypassword"
